DROP TABLE AEROLINEAS;
CREATE TABLE AEROLINEAS (
ID_AEROLINEA INT PRIMARY KEY NOT NULL, 
NOMBRE_AEROLINEA VARCHAR(20));

DROP TABLE AEROPUERTOS;
CREATE TABLE AEROPUERTOS(
ID_AEROPUERTO INT PRIMARY KEY NOT NULL,
NOMBRE_AEROPUERTO VARCHAR(20));

DROP TABLE MOVIMIENTOS;
CREATE TABLE MOVIMIENTOS(
ID_MOVIMIENTO INT PRIMARY KEY NOT NULL,
DESCRIPCION VARCHAR(10));

DROP TABLE VUELOS;
CREATE TABLE VUELOS(
ID_AEROLINEA INT ,
ID_AEROPUERTO INT,
ID_MOVIMIENTO INT ,
DIA timestamp,
FOREIGN KEY (ID_AEROLINEA) REFERENCES AEROLINEAS(ID_AEROLINEA),
FOREIGN KEY (ID_AEROPUERTO) REFERENCES AEROPUERTOS(ID_AEROPUERTO),
FOREIGN KEY (ID_MOVIMIENTO) REFERENCES MOVIMIENTOS(ID_MOVIMIENTO));
